[package]
name = "csv-migrator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive", "cargo"] }
colored = "3.0.0"
csv = "1.3.1"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
strip = true
